Adds bin2hex optional to random auth key.
AfriCC/php-epp2 pull request #55
Opened 2017-10-27 22:41 UTC by peternicholls

This is a non-breaking change.

The function can be called exactly as
previously with no changes to functionality.

The addition of the optional second parameter as TRUE simply converts
the paramater $randomBytes to hex instead of base64 encoding.

2017-10-28 14:47 UTC, lifeofguenter requested changes
thanks @peternicholls !

Question: why is this being needed?

2017-10-28 14:47 UTC, lifeofguenter commented on src/AfriCC/EPP/Random.php
> +    public static function auth($len, $hex = '')
`$hex = false`

2017-10-28 14:47 UTC, lifeofguenter commented on src/AfriCC/EPP/Random.php
> +        if (TRUE == $hex) {
`if ($hex) {`

2017-10-29 05:39 UTC, peternicholls commented
I was being naive.

2017-10-29 05:39 UTC, closed without merging

2017-10-29 05:41 UTC, peternicholls commented
I was being naive. I think there is far better way to do this. And I like having the option to have bytes encoding.

2017-10-29 05:44 UTC, peternicholls commented
My proposal is that rather than a flag, which gets messy and isn’t self documentating, the code abstracts out to a factory function, which can be called by the current code which calling function producing base64, and a hex calling function.